import time

print("Welcome to TTYD!")
input("Always press ENTER to continue...")
print("Go buy this game from Nintendo, it is awesome!!")
input()
print("We all know the opening book sequence. Imagine the book and backstory and boat and dialogue...")
input()
print("It's so beautiful!")
input()
print("Alright enough startup, Mario gets dropped off at the Rogueport Docks.")
input()
print("In this tool, you move by inputting your actions as numbers. Press ENTER to continue...")
input()
print("-----ROGUEPORT DOCKS-----")
print("What would you like to do?")
print("1. Go into town")
print("2. Save")
